import { Database, ExternalLink } from 'lucide-react';
import type { ReactNode } from 'react';

interface SourceLink {
  label: string;
  href?: string;
  note?: string;
}

interface Props {
  /** Short summary, e.g. "Aggregated from 467 candidate records." */
  summary?: ReactNode;
  /** Concrete sources backing the data on this page. */
  sources: SourceLink[];
  /** When the source data was last generated, if known. */
  generatedAt?: string;
}

const REPO_ROOT = 'https://github.com/anastluc/cyprus-elections-2026';

export function DataSource({ summary, sources, generatedAt }: Props) {
  return (
    <section
      aria-label="Data sources"
      className="mt-10 rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-xs text-slate-400"
    >
      <header className="mb-2 flex items-center gap-2">
        <Database className="h-3.5 w-3.5 text-brand-400" />
        <span className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-300">
          Data source
        </span>
        {generatedAt ? (
          <span className="ml-auto text-[10px] text-slate-500">
            Generated {new Date(generatedAt).toLocaleString()}
          </span>
        ) : null}
      </header>
      {summary ? <p className="mb-2 leading-relaxed text-slate-300">{summary}</p> : null}
      <ul className="flex flex-wrap gap-x-4 gap-y-1">
        {sources.map((s, i) => (
          <li key={i} className="inline-flex items-center gap-1">
            {s.href ? (
              <a
                href={s.href}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1 text-brand-300 hover:text-brand-200"
              >
                {s.label}
                <ExternalLink className="h-3 w-3" />
              </a>
            ) : (
              <span className="text-slate-300">{s.label}</span>
            )}
            {s.note ? <span className="text-slate-500">— {s.note}</span> : null}
          </li>
        ))}
      </ul>
    </section>
  );
}

export const DATASET_SOURCE_LINK: SourceLink = {
  label: 'dashboard/public/data/*.json',
  href: `${REPO_ROOT}/tree/main/dashboard/public/data`,
  note: 'generated by `uv run cyprus-elections export --format dashboard`',
};

export const CANDIDATES_SOURCE_LINK: SourceLink = {
  label: 'candidates.json',
  href: `${REPO_ROOT}/blob/main/dashboard/public/data/candidates.json`,
  note: 'per-candidate fields, each with provenance pill on the profile page',
};

export const STATS_SOURCE_LINK: SourceLink = {
  label: 'stats.json',
  href: `${REPO_ROOT}/blob/main/dashboard/public/data/stats.json`,
  note: 'aggregates computed from candidates.json',
};

export const HISTORY_SOURCE_LINK: SourceLink = {
  label: 'history.json',
  href: `${REPO_ROOT}/blob/main/dashboard/public/data/history.json`,
  note: 'historical election results scraped from MOI / Wikipedia',
};

export const PIPELINE_SOURCE_LINK: SourceLink = {
  label: 'enrichment pipeline',
  href: `${REPO_ROOT}/tree/main/src/cyprus_elections/enrich`,
  note: 'web scraping + LLM extraction',
};
